### PR TITLE
Conforming to the new structure (Multiple responses from the same app in the merged JSON)

### PR DESCRIPTION
**Pull request by Mihaiii**
Related to https://github.com/Starcounter/level1/issues/4061  and Issue #3 .

### CODE REVIEW

**Comment by warpech** [comment]
I will also review

**Comment by warpech** [comment]
Thank you @Mihaiii for a super fast response. 

The demo at https://github.com/StarcounterApps/Content/blob/b04149a45cf88ad32de8e867a43e2efdf26edb99/src/Content/ViewModels/AppName.json is more complex than I assumed. 

The two icons should be two independent views (with 3 properties `name`, `description`, `html`) mapped to the same token `app-name`.

Does it simplify this PR?

**Comment by Mihaiii** [comment]
That is the first thing I tried, but only the last json that is mapped to `app-name` gets to Launchpad.
Please allow me few minutes to look into this is that is the correct solution.

**Comment by Mihaiii** [comment]
@warpech Did you meant something like what is on this branch:
https://github.com/StarcounterApps/Content/tree/demo/multiple-icons ?

**Comment by warpech** [comment]
Yes, that branch is exactly what I mean.

**Comment by Mihaiii** [comment]
Thank you for the reply! 
It helps me know that I didn't do something that wasn't expected.

**Comment by Mihaiii** [comment]
Closing as not needed anymore.

**Pull request closed without merging**
