### PR TITLE
Add common settings page #18

### LINKED ISSUE #18: Common settings page
Launchpad should implement the proposal from https://github.com/Starcounter/Guidelines/issues/33

@bouguila could you please implement this? 

You can take the cog icon from our old [Launcher](https://github.com/StarcounterAppsFreezer/Launcher/blob/master/src/Launcher/wwwroot/Launcher/images/cog.svg) app, just remember that it should pasted inline in HTML.

Suggested reviewer: @Mihaiii

### PR DESCRIPTION
**Pull request by bouguila**
Fix #18

### CODE REVIEW

**Comment by Mihaiii** [comment]
I guess that the Settings Page should look more like the one in Launcher https://github.com/StarcounterAppsFreezer/Launcher/blob/master/src/Launcher/wwwroot/Launcher/viewmodels/SettingsPage.html .

There is also a universal Save button, that has a `Transaction.Commit()` when pressed. 
Just as a side note, this PR seems related to https://github.com/Starcounter/Guidelines/issues/27 .

I think there should be some extra CSS for a better look when we get multiple Settings Page.

**Comment by bouguila** [comment]
@Mihaiii i'm not sure that **Launchpad**'s setting page should have `save` and `cancel` buttons since it has nothing to transact itself which was not the case with **Launche**r App.

**Comment by warpech** [comment]
In https://github.com/Starcounter/Guidelines/issues/27 we have only agreed on points 1-3, so I don't think it is necessary to add the Save and Cancel buttons.

The inline SVG icon looks ok, though I didn't run it. I trust it works ok.

**Comment by bouguila** [comment]
thanks @Mihaiii and @warpech 
merging now.

**Pull request merged**
