### PR TITLE
Extract Launchpad from the Launcher

### PR DESCRIPTION
**Pull request by un-tone**
For https://github.com/StarcounterApps/Launcher/issues/267

### CODE REVIEW

**Comment by warpech** [comment]
It works amazingly well combined with https://github.com/StarcounterApps/Launcher/pull/275, but I could not get this to work with Website. 

Tried the following steps:

1. Start Website & WebsiteProvider using `build.bat`, `run.bat` from the `develop` branch
2. Start Launchpad using `build.bat`, `run.bat` from the `develop` branch
3. Start KitchnenSink using `build.bat`, `run.bat` from the `develop` branch
4. Go to `http://localhost:8080/kitchensink`
5. Click on the KitchenSink icon

This results with an error:

```txt
Uncaught TypeError: Cannot read property 'CurrentPage' of undefined
    at Object.apply (json-patch-duplex.js:473)
    at PuppetDOM.Puppet.validateAndApplySequence (puppet.js:703)
    at applyOT (json-patch-ot-agent.js:83)
    at JSONPatchOTAgent.JSONPatchQueue.receive (json-patch-queue.js:74)
    at JSONPatchOTAgent.receive (json-patch-ot-agent.js:57)
    at PuppetDOM.Puppet.handleRemoteChange (puppet.js:794)
    at PuppetDOM.<anonymous> (puppet.js:401)
    at XMLHttpRequest.req.onload (puppet.js:441)
```

@un-tone any clues?

2017-03-09 21_36_37-launchpad

**Comment by un-tone** [comment]
@warpech there are issues with merging in the Website app. I assume we should create a new issue for this bug.

**Comment by warpech** [comment]
Can you isolate the problem and create an issue for that?

**Comment by mmnosek** [comment]
Hi guys, just want to ask - do we cover a feature that allows including more icons in launchpad from one app (SWO case)?

**Comment by un-tone** [comment]
@warpech created https://github.com/StarcounterApps/Website/issues/63

**Comment by warpech** [comment]
@un-tone I think this is ready to release. If you agree, please merge and release 1.0.0

**Comment by un-tone** [comment]
Merged and released.

**Pull request merged**
